### PR TITLE
Added Userinfo command and Fixed Args check in reload command 

### PR DESCRIPTION
**Pull request by MrJacz**
Title says it all <3

### CODE REVIEW

**Comment by MrJacz** [comment]
Codacy :feelsgood:

**Comment by DeJayDevelopment** [comment]
Life pro tip, click the details button next to codacy's comment. He tells you what to fix. 😉

**Comment by MrJacz** [comment]
@DeJayDevelopment Yeah i did fix most issues tho but i dont think evie has setup the Pattern's cause the code is 👍

**Comment by eslachance** [comment]
Uhhhhhhhhhh ` args.size < 0` wat. Please re-submit *without* the changes to the reload command.

**Comment by MrJacz** [comment]
Well i fixed the args on reload @eslachance

**Comment by ohlookitsderpy** [comment]
mmLol

**Pull request merged**
