### PR TITLE
Update playing.js

### PR DESCRIPTION
**Pull request by JohnDoesCodes**
**Updated**

Please pull this, D.js updated there playing status.

### CODE REVIEW

**Comment by eslachance** [comment]
Template literals should not be used when they're not combined with stings. ```js
const blah = `${othervar}`
```

I don't know why everyone's so obsessed with damn Template Literals. `setPresence({ game: { name: game, type: 0 } })` is perfectly valid. Please fix.

**Comment by eslachance** [comment]
One more thing. Codacy checks are actually pretty useful if you're not using any linter in your editor (I'll be making a video on this soon btw). In this case, you're missing a semicolon at the end of the line ;)

**Comment by JohnDoesCodes** [comment]
alrighty

**Comment by JohnDoesCodes** [comment]
What's up with this updates tho? I mean is this how you send embeds now?
`message.channel.send(new RichEmbed().setTitle('Test'));`

**Comment by JohnDoesCodes** [comment]
oh and **Codacy** is useful.

**Pull request merged**
